// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MathRecognitionServiceIdentityDB.Data.MathRecognitionServiceIdentity;

public partial class MathRecognitionServiceIdentityContext : DbContext
{
    public MathRecognitionServiceIdentityContext(DbContextOptions<MathRecognitionServiceIdentityContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Recognition> Recognitions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Recognition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Recognit__3213E83F4DDED60C");

            entity.Property(e => e.ImagePath).IsRequired();
            entity.Property(e => e.Json).IsRequired();
            entity.Property(e => e.DateTime);
            entity.Property(e => e.UserName)
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}